# Generated by Django 3.1 on 2020-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('locate', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('insta', models.TextField(null=True)),
            ],
        ),
    ]
